package com.psl.utils;

/**
 * LogMessages</br>
 * Class that hosts the log messages generated by the application.
 * */
public class LogMessages {
    /** MSG Failed to retrieve records*/
    public static final String MSG_INFO_NOT_FOUNT_RECORDS       = "Failed to retrieve records from path supplied %s.";
    /** MSG The output file is created*/
    public static final String MSG_INFO_CREATE_OUTPUT_FILE      = "The out.txt file is created in path %s.";
    /** MSG Could not create output file*/
    public static final String MSG_INFO_NO_CREATE_OUTPUT_FILE   = "It was not possible to create the out.txt file in path %s.";

    /** MSG Unexpected error has occurred while writing.*/
    public static final String MSG_ERROR_WRITE_IN_OUTPUT_FILE   = "An unexpected error has occurred while writing to file ";
    /** MSG Unexpected error while reading file.*/
    public static final String MSG_ERROR_READ_INPUT_FILE        = "Unexpected error while reading file %s.";

    /** MSG Unexpected error while reading file.*/
    public static final String MSG_INFO_REGISTRATION_PARAMETERS = "The registration parameters %s are not valid";
    /** MSG Number printer.*/
    public static final String MSG_INFO_NUMBER_PRINTER          = "Number %s with size %s has been printed";
    /** MSG Number printer.*/
    public static final String MSG_INFO_FINAL_RECORD_PROCESSED  = "Final record processed  %s";
    /** MSG Print line*/
    public static final String MSG_INFO_PRINT_LINE              = "Print the line %s";
    /** MSG Default paths files*/
    public static final String MSG_INFO_DEFAULT_PATHS           = "No input routes are provided so they take the default values, inputpah: %s , outputtpah: %s ";
    /** MSG Invalid paths*/
    public static final String MSG_INFO_INVALID_PATHS           = "Invalid paths, inputpah: %s , outputtpah: %s ";

}
